CREATE DATABASE IF NOT EXISTS examen_voertuigenbeheer CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE examen_voertuigenbeheer;

CREATE TABLE IF NOT EXISTS users (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50) NOT NULL UNIQUE,
 email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS voertuigen (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL,
 kenteken VARCHAR(20) NOT NULL UNIQUE, merk VARCHAR(80) NOT NULL, model VARCHAR(100) NOT NULL,
 bouwjaar SMALLINT UNSIGNED NOT NULL, kilometerstand INT UNSIGNED NOT NULL DEFAULT 0,
 status ENUM('Actief','In onderhoud','Buiten gebruik') NOT NULL DEFAULT 'Actief',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_voertuigen_user (user_id),
 CONSTRAINT fk_voertuig_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS onderhoud (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, voertuig_id INT UNSIGNED NOT NULL,
 omschrijving VARCHAR(255) NOT NULL, onderhoudsdatum DATE NOT NULL,
 kosten DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0,
 status ENUM('Gepland','Uitgevoerd','Geannuleerd') NOT NULL DEFAULT 'Gepland',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_onderhoud_voertuig (voertuig_id),
 CONSTRAINT fk_onderhoud_voertuig FOREIGN KEY (voertuig_id) REFERENCES voertuigen(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS audit_log (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NULL,
 actie VARCHAR(40) NOT NULL, entiteit VARCHAR(40) NOT NULL, entiteit_id INT UNSIGNED NULL,
 details VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_audit_user_voertuigen FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
